# Generated by Django 6.0.1 on 2026-01-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                ("slug", models.SlugField(max_length=32, unique=True)),
                ("release_date", models.DateField()),
                ("price", models.PositiveIntegerField()),
                ("image", models.URLField(max_length=128, unique=True)),
                ("lte_exists", models.BooleanField()),
            ],
        ),
    ]
