# Generated by Django 6.0.1 on 2026-01-15 03:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
                "default_related_name": "%(model_name)ss",
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("address", models.CharField(max_length=256, unique=True)),
            ],
            options={
                "ordering": ["address"],
                "abstract": False,
                "default_related_name": "%(model_name)ss",
            },
        ),
        migrations.CreateModel(
            name="WarehouseItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("unit_cost", models.PositiveIntegerField()),
                ("quantity", models.PositiveIntegerField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hw6.item"
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hw6.warehouse"
                    ),
                ),
            ],
            options={
                "ordering": ["warehouse", "item"],
                "abstract": False,
                "default_related_name": "%(model_name)ss",
                "unique_together": {("warehouse", "item")},
            },
        ),
        migrations.AddField(
            model_name="warehouse",
            name="items",
            field=models.ManyToManyField(through="hw6.WarehouseItem", to="hw6.item"),
        ),
    ]
